# Generated by Django 4.2.7 on 2024-11-01 08:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('barcode', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$')], verbose_name='Штрих-код')),
                ('purchase', models.IntegerField(verbose_name='Закуп')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категория')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.heroes', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'db_table': 'supplies',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('barcode', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$')], verbose_name='Штрих-код')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('total_discount', models.IntegerField(default=0, verbose_name='Суммарная скидка')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категория')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.heroes', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales',
                'ordering': ('id',),
            },
        ),
    ]
