# Generated by Django 4.2.7 on 2024-11-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_products_title'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='date',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='purchase',
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Товар'),
        ),
        migrations.AddField(
            model_name='supplies',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Товар'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_operation', models.BooleanField(verbose_name='INCOME')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('barcode', models.CharField(max_length=13, verbose_name='Штрих-код')),
                ('quantity', models.IntegerField(verbose_name='Кол-во')),
                ('purchase', models.IntegerField(verbose_name='Закуп')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('total_discount', models.IntegerField(default=0, verbose_name='Суммарная скидка')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.heroes', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'db_table': 'journal',
                'ordering': ('-id',),
            },
        ),
    ]
