# Generated by Django 4.2.7 on 2024-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_sales_quantity_alter_supplies_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Итог'),
        ),
    ]
