# Generated by Django 4.2.7 on 2024-11-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_journal_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='balance',
        ),
    ]
